login/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
##app
from secondmall import views

from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve
from login.settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index),
    path('', views.index),
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
    path('login/', views.login),
    path('register/', views.register),
    path('logout/', views.logout),
    path('captcha/', include('captcha.urls')),
    path('test/', views.UploadGoodsView.as_view()),
    path('upload/',views.upload),
    path('sell_record/', views.sell_record),
    path('buy_record/', views.buy_record),
    path('cart/', views.cart),
    path('changeInfo/', views.changeInfo),
    url(r'^goodsInfo/(\d+)/$', views.goodsInfo,name='goodsInfo'),
    path('buy_goods/', views.buy_goods),
    path('return_goods/', views.return_goods),
    path('cart_goods/',views.cart_goods),
    path('return_carts/',views.return_cart)
    

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

secondmall/models.py
import uuid

from django.db import models

# Create your models here.
#superuser: huang hcw1998HCW


class User(models.Model):
    gender = (
        ('male','男'),
        ('female','女'),
    )
    name = models.CharField(max_length=128,unique=True)
    pwd = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    sex = models.CharField(max_length=32,choices=gender,default='male')
    c_time = models.DateTimeField(auto_now_add=True)
    iden = (
        (0,'买家'),
        (1,'卖家'),
    )
    type = models.SmallIntegerField(verbose_name='身份',choices=iden,default=0)
    phoneNumber = models.CharField(max_length=11,verbose_name='手机号码',default='')
    birth = models.DateField(blank=True)
    def __str__(self):
        return self.name
    

    class Meta:
        ordering = ['-c_time']
        verbose_name = '用户'
        verbose_name_plural = '用户'

#商品
class Goods(models.Model):
    name = models.CharField(max_length=128)
    seller = models.ForeignKey('User',on_delete=models.CASCADE,blank=True,default='') #级联删除
    price = models.FloatField(default=0, null=False)
    img = models.ImageField(upload_to='goods_img')
    descrip = models.TextField(max_length=1024,default='',blank=True)

    stats = ((0,'未售'),(1,'已售'),)
    state = models.SmallIntegerField(choices=stats,default=0,blank=True)
    types = (
        (0,'服装'),
        (1,'电子产品'),
        (2,'书籍'),
    ) ##todo
    type = models.SmallIntegerField(choices=types, default=0)


"""
# 评论 买方和货物的关系
class Comments(models.Model):
    user = models.ForeignKey('User',on_delete=models.CASCADE)
    goods = models.ForeignKey('Goods',on_delete=models.CASCADE)
    content = models.TextField()##to do
    date = models.DateField()



#卖方对商品的所属关系
class seller_have(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    goods = models.ForeignKey('Goods', on_delete=models.CASCADE)
    date = models.DateField()
"""
#购物车，买方与货物的所属关系
class cart(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    goods = models.ForeignKey('Goods', on_delete=models.CASCADE)
    date = models.DateTimeField()

    class Meta:
        unique_together = ('user', 'goods')
    
#买方对商品的所属关系
class buy_record(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    goods = models.ForeignKey('Goods', on_delete=models.CASCADE)
    date = models.DateTimeField()
    

#交易记录

class deal(models.Model):
    buyer = models.ForeignKey('User', on_delete=models.CASCADE,related_name='buyer')
    seller = models.ForeignKey('User', on_delete=models.CASCADE,related_name='seller')
    goods = models.ForeignKey('Goods', on_delete=models.CASCADE)
    date = models.DateTimeField()
    price = models.FloatField(default=0, null=False)



class Article(models.Model):
    #ids = models.AutoField(primary_key=True, default=0)
    myfile = models.ImageField(upload_to="test")

secondmall/views.py
from django.http import JsonResponse
from django.shortcuts import render,redirect
from . import models, forms
from .util import *
from django.views.generic import View
from django.http import HttpResponse

from django.contrib import messages
# Create your views here.

##加密密码
import hashlib
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
def hash_code(s,salt = 'mysite'):
    h = hashlib.sha256()
    s += salt
    h.update(s.encode())
    return h.hexdigest()


def index(request):
    allgoods = models.Goods.objects.filter()
    if not request.session.get('is_login', None):
        return redirect('/login/')
    if request.session['user_type'] == 0:
        return render(request, 'user/base_buyer.html',locals())
    elif request.session['user_type'] == 1:
        return render(request,'user/base_sell.html',locals())

    #return render(request, 'user/index.html')

def login(request):
    if request.session.get('is_login',None):
        return redirect('/index/')
    if request.method == 'POST':
        login_form = forms.UserForm(request.POST)
        message = '请检查填写的内容！'
        if login_form.is_valid():
            username = login_form.cleaned_data.get('username')
            password = login_form.cleaned_data.get('password')

            try:
                user = models.User.objects.get(name=username)
            except :
                message = '用户不存在！'
                return render(request, 'user/login.html', locals())

            if user.pwd == password:
                request.session['is_login'] = True
                request.session['user_id'] = user.id
                request.session['user_name'] = user.name
                request.session['user_type'] = user.type
                type = user.type
                return redirect('/index/')
            else:
                message = '密码不正确！'
                return render(request, 'user/login.html', locals())
        else:
            return render(request, 'user/login.html', locals())
    # 通过forms中的类将变量传给html
    login_form = forms.UserForm()
    return render(request, 'user/login.html', locals())


def logout(request):
    if not request.session.get('is_login',None):
        return redirect('/login/')
    request.session.flush()

    return redirect('/logout/')


def register(request):
    if request.session.get('is_login',None):
        return redirect('/index/')
    
    if request.method == 'POST':
        #print('in post')
        register_form = forms.RegisterForm(request.POST)
        message = '输入不合法！'
        
        if register_form.is_valid():
            username = register_form.cleaned_data.get('username')
            pwd1 = register_form.cleaned_data.get('password1')
            pwd2 = register_form.cleaned_data.get('password2')
            type = register_form.cleaned_data.get('type')
            email = register_form.cleaned_data.get('email')
            sex = register_form.cleaned_data.get('sex')
            birth = register_form.cleaned_data.get('birth')
            phoneNumber = register_form.cleaned_data.get('phoneNumber')
            # 检测输入密码是否一致
            if pwd1 != pwd2:
                message = '两次密码不同！'
                return render(request,'user/register.html', locals())
            elif len(pwd1) == 0:
                message = '密码不能为空！'
                return render(request,'user/register.html',locals())
            elif not judge_Monile_phone(phoneNumber):
                message = '手机号格式错误！'
                return render(request,'user/register.html',locals())

            # 检查身份，是否重复
            else:
                same_user = models.User.objects.filter(name=username)
                if same_user:
                    message = '用户名已存在！'
                    return render(request,'user/register.html',locals())
                same_email = models.User.objects.filter(email=email)
                if same_email:
                    message = '邮箱已存在！'
                    return render(request,'user/register.html',locals())
                new_user = models.User()
                new_user.name = username
                #new_user.pwd = hash_code(pwd1)
                new_user.pwd = pwd1
                new_user.email = email
                new_user.sex = sex
                new_user.type = type
                new_user.phoneNumber = phoneNumber
                new_user.birth = birth
                new_user.save()
                return redirect('/login/')
        #注册表无效
        else:
            return render(request,'user/register.html',locals())

    register_form = forms.RegisterForm()
    return render(request, 'user/register.html',locals())


class UploadGoodsView(View):
    # 如果是GET请求，直接渲染到上传文件页面
    def get(self, request):
        return render(request, 'user/test.html')
    # 如果是POST请求，那么将接收文件的值
    def post(self, request):
        # 获取前台传来的文件，request.POST用来接收title和content，request.FILES用来接收文件
        form = forms.ArticleForm(request.POST, request.FILES)
        # 将数据保存到数据库orm cl
        if form.is_valid():
            print('clean data',form.cleaned_data)
            form.save()
            return HttpResponse("SUCCESS")
        else:
            # 打印错误信息
            print(form.errors.get_json_data())
            return HttpResponse("Fail")

def upload(request):
    #未登录无法上传
    if not request.session.get('is_login',None):
        #print('1 upload session')
        return redirect('/index/')
    
    if request.method == 'POST':
        form = forms.Upload(request.POST, request.FILES)
        # 将数据保存到数据库
        if form.is_valid():
            newgoods = form.save(commit=False)
            seller = models.User.objects.get(pk=request.session.get('user_id'))
            newgoods.seller_id = request.session.get('user_id')
            newgoods.save()
            #messages.success(request, "上传成功")
            print('here!!')
            return redirect('/index/')
        else:
            print(form.errors.get_json_data())
            #messages.success(request, "上传失败")
            return redirect('/upload/')
    form = forms.Upload()
    return render(request, 'user/uploadgoods.html', locals())

def sell_record(request):
    return render(request, 'user/sell_record.html', locals())

def buy_record(request):
    if not request.session.get('is_login',None):
        return redirect('/login/')
    buy_records = models.deal.objects.filter(buyer_id=request.session.get('user_id'))
    return render(request, 'user/buy_record.html', locals())

def cart(request):
    if not request.session.get('is_login',None):
        return redirect('/login/')
    carts = models.cart.objects.filter(user_id=request.session.get('user_id'))
    return render(request, 'user/cart.html', locals())

def changeInfo(request):
    #未登录 返回登陆界面
    if not request.session.get('is_login', None):
        return redirect('/login/')
    #print(1)

    if request.method == 'POST':
        form = forms.InfoForm(request.POST)
        message = '输入不合法！'

        if form.is_valid():
            username = form.cleaned_data.get('username')
            pwd1 = form.cleaned_data.get('password1')
            pwd2 = form.cleaned_data.get('password2')
            email = form.cleaned_data.get('email')
            birth = form.cleaned_data.get('birth')
            phoneNumber = form.cleaned_data.get('phoneNumber')
            # 检测输入密码是否一致
            if pwd1!=pwd2:
                message = '两次密码不同'
                return render(request,'user/changeInfo.html',locals())
            elif len(pwd1) == 0:
                message = '密码不能为空！'
                return redirect('/changeInfo/')
            elif not judge_Monile_phone(phoneNumber):
                message = '手机号格式错误！'
                return render('/changeInfo/')
            else:
                now_user = set(models.User.objects.filter(pk=request.session['user_id']))
                same_user = set(models.User.objects.filter(name=username))-now_user

                if same_user:
                    message = '用户名已存在！'
                    return render(request, 'user/changeInfo.html', locals())
                same_email = set(models.User.objects.filter(email=email))-now_user
                if same_email:
                    message = '邮箱已存在！'
                    return render(request,'user/changeInfo.html',locals())
                #print('change here!!!!!!')

                new_user = models.User.objects.filter(pk=request.session['user_id'])[0]
                #print('new_user!!!!!!!!',new_user)
                new_user.name = username
                new_user.pwd = hash_code(pwd1)
                new_user.email = email
                new_user.phoneNumber = phoneNumber
                new_user.birth = birth
                new_user.save()
                request.session['user_name'] = username
                #修改成功
                return redirect('/index/')
        # 注册表无效
        else:
            message = '输入不合法！'
            print('invalid')
            return render(request, 'user/changeInfo.html', locals())
    else:
        ids = request.session['user_id']
        now_user = models.User.objects.get(id=ids)
        dic = {'username':now_user.name,'email':now_user.email,'phoneNumber':now_user.phoneNumber,'birth':now_user.birth,
               'password1':now_user.pwd,'password2':now_user.pwd}
        
        form = forms.InfoForm(initial=dic)
        return render(request, 'user/changeInfo.html', locals())
    
def goodsInfo(request,id):
    goods = models.Goods.objects.get(id=id)
    return render(request,'goods/goodsInfo.html',locals())

@csrf_exempt
def buy_goods(request):
    if request.method == 'POST':
        goods_id = request.POST.get('goods_id')
        #print('goods_id',goods_id)
        seller_id = request.POST.get('seller_id')
        goods = models.Goods.objects.get(id=goods_id)
        price = goods.price
        # 已售出
        if goods.state == 1:
            #print('已售出')
            return JsonResponse({'status': 200, 'message': '商品已出售'})

secondmall/templates/user/base_buyer.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Buyer</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'user/css/buyer.css' %}" rel="stylesheet"/>
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>


</head>

<body>

<div class="container-fluid">

        <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
{#            ？？？#}
          <a class="navbar-brand" href="#">真咸鱼</a>
        </div>
         <form class="navbar-form navbar-right">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="搜索你想要的商品">
        </div>
        <button type="submit" class="btn btn-default">搜索</button>
      </form>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul class="nav navbar-nav navbar-right">
            <li><a href="/cart/">购物车</a></li>
{#              ？？？#}
              <li><a href="/buy_record/">购买记录</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.session.user_name }} <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/logout/">登出</a></li>
                <li><a href="/changeInfo/">维护个人信息</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="row">
        <img src="/static/user/image/title.png" class="img-responsive">
    </div>

    <hr align="center">

    <div class="container">



<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="/static/user/image/b.png" alt="..." class="img-responsive">
      <div class="carousel-caption">
      </div>
    </div>
    <div class="item">
      <img src="/static/user/image/c.png" alt="..." class="img-responsive">
      <div class="carousel-caption">
      </div>
    </div>

      <div class="item">
      <img src="/static/user/image/i.png" alt="..." class="img-responsive">
      <div class="carousel-caption">
      </div>
    </div>

  </div>



  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
        </div>

    <div class="container">
        <div class="row line">
            <span>热门商品</span>
        </div>
    </div>


<div class="container goodstop">
    <div class="row">
        {% for goods in allgoods %}
        <div class="col-sm-6 col-md-3">
            <div class="thumbnail">
            <img src="/media/{{ goods.img }}" width="216" height="216" alt="暂无图像">
                <div class="caption">

                <h3>名称: {{ goods.name }}</h3>

                <p>价格 {{ goods.price }}元</p>

                <p>上传者 {{ goods.seller.name }}</p>

                    <p>商品状态 {{ goods.get_state_display }}</p>
                 <p><a href="{% url 'goodsInfo' goods.id  %}">商品详情</a></p>

               </div>
            </div>
        </div>
        {% endfor %}


    </div>

    <nav aria-label="Page navigation" class="nav2">
        <ul class="pagination">
            <li>
                <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li>
                <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>

    </div>

    <br>
    <br>
    <br>
    <br>
    <br>

    <div class="row company">
        真咸鱼二手交易平台，All Rights Reserved
    </div>

</div>
</body>
</html>

secondmall/templates/user/base_sell.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Seller</title>

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="{% static 'user/css/seller.css' %}" rel="stylesheet"/>
    <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>




</head>

<body>

<div class="container-fluid">

        <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
{#            ？？？#}
          <a class="navbar-brand" href="#">真咸鱼</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <ul class="nav navbar-nav navbar-right">
            <li><a href="/upload/">上传商品</a></li>
{#              ？？？#}
              <li><a href="/sell_record/">出售记录</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ request.session.user_name }} <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="/logout/">登出</a></li>
                <li><a href="/changeInfo/">维护个人信息</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <div class="row">
        <img src="/static/user/image/title.png" class="img-responsive">
    </div>

    <hr align="center">

    <div class="container">
        <div class="row line">
            <span>我的货架</span>
        </div>
    </div>

    <div class="container goodstop">
    <div class="row">
        {% for goods in allgoods %}
        <div class="col-sm-6 col-md-3">
            <div class="thumbnail">
            <img src="/media/{{ goods.img }}" width="216" height="216" alt="暂无图像">

                <div class="caption">

                <h3>名称 {{ goods.name }}</h3>

                <p>价格 {{ goods.price }}元</p>

                <p>上传者 {{ goods.seller.name }}</p>
                <p>商品状态 {{ goods.get_state_display }}</p>
                <p><a href="{% url 'goodsInfo' goods.id  %}">商品详情</a></p>
                <p><a href="#" class="btn btn-primary button1-left" role="button">商品下架</a> <a href="#" class="btn btn-default button2-left" role="button">修改信息</a></p>
                </div>
            </div>
        </div>
        {% endfor %}


    </div>


    <nav aria-label="Page navigation" class="nav2">
        <ul class="pagination">
            <li>
                <a href="#" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li><a href="#">1</a></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li>
                <a href="#" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>

    </div>

    <br>
    <br>
    <br>
    <br>
    <br>

    <div class="row company">
        真咸鱼二手交易平台，All Rights Reserved
    </div>

</div>
</body>
</html>

secondmall/templates/user/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
<p>
    <a href="/logout/">登出</a>
</p>
<p>
    <a href="/test/">修改身份</a>
</p>
<p>
    <a href="/upload/">上传商品</a>
</p>
</body>
</html>

secondmall/templates/user/login.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- 上述meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <!-- Bootstrap CSS -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'user/css/login.css' %}" rel="stylesheet"/>
    <title>登录</title>
  </head>
  <body>
    <div class="container">
        <div class="container-left">
            <img src="/static/user/image/logo.png" class="logo">
            <p class="tip">登录</p>
            <p>LOG IN</p>
        </div>
            <div class="col">
                <form class="form-login" action="/login/" method="post">

                {% if login_form.captcha.errors %}
                    <div class="alert alert-warning">{{ login_form.captcha.errors }}</div>
                {% elif message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}

                  {% csrf_token %}


                  <div class="form-group">
                    {{ login_form.username.label_tag }}
                    {{ login_form.username}}
                  </div>

                  <div class="form-group">
                    {{ login_form.password.label_tag }}
                    {{ login_form.password }}
                  </div>

                  <div class="form-group">
                    {{ login_form.captcha.label_tag }}
                    {{ login_form.captcha }}
                  </div>

                  <div>
                      <a href="/register/" class="text-success " ><ins>新用户注册</ins></a>
                      <button type="submit" class="btn btn-primary float-right">登录</button>
                  </div>
                </form>
            </div>
    </div> <!-- /container -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    {#    引用顺序是固定的#}
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.15.0/umd/popper.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/4.3.1/js/bootstrap.min.js"></script>

  </body>
</html>

secondmall/templates/user/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>商品上传页</title>
</head>
<body>

{#enctype="multipart/form-data"文件编码方式，必须设置，否则文件无法上传#}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="title">
    <input type="text" name="content">
    <input type="file" name="myfile">
    <input type="submit" value="提交">
</form>

</body>
</html>